# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lrm_coef <- function(X, Y) {
    .Call('_lrm_lrm_coef', PACKAGE = 'lrm', X, Y)
}

